kind: Deployment
apiVersion: {{ template "babibe.deployment.apiVersion" . }}
metadata:
  name: {{ template "babibe.fullname" . }}
  namespace: {{ template "babibe.namespace" . }}
  labels: {{ include "babibe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: {{ include "babibe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "babibe.labels" . | nindent 8 }}
    spec:
      containers:
      {{- range $container := .Values.containers }}
      - name: {{ $container.name }}
        imagePullPolicy: {{ $container.imagePullPolicy }}
        {{- if $container.workingDir }}
        workingDir: {{ $container.workingDir }}
        {{- end }}
        {{- with $container.image }}
        {{- if .tag }}
        image: {{ .repository }}:{{ .tag }}
        {{- else }}
        image: {{ .repository }}@{{ .digest }}
        {{- end }}
        {{- end }}
        {{- with $container.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $container.volumeMounts }}
        volumeMounts: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $container.command }}
        command: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $container.env }}
        env: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $container.ports }}
        ports: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $container.args }}
        args: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases: {{ toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}