{{- range $imageStream := .Values.imageStreams -}}
{{- with $imageStream -}}
kind: ImageStream
apiVersion: {{ template "babibe.imageStream.apiVersion" $ }}
metadata:
  name: {{ .name }}
  namespace: {{ template "babibe.namespace" $ }}
  labels: {{ include "babibe.labels" . | nindent 4 }}
spec:
  lookupPolicy: {{ toYaml .lookupPolicy | nindent 4 }}    
{{- end }}
{{- end }}